import { copyFileSync, readFileSync, writeFileSync } from "fs"
import { resolve } from "path"
import {
  envFileName,
  requireEnvFile,
  resolveAppEnv,
  type AppEnv,
} from "@/lib/env/app-env"

const parseCliEnv = (): string | null => {
  const args = process.argv.slice(2)
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    if (arg === "--env" || arg === "-e") {
      return args[i + 1] ?? null
    }
    if (arg.startsWith("--env=")) {
      return arg.slice("--env=".length)
    }
  }
  return null
}

const selectEnv = () => {
  const resolved = resolveAppEnv(parseCliEnv())
  const { env, source, branch } = resolved
  const sourcePath = requireEnvFile(env)
  const targetPath = resolve(process.cwd(), ".env.local")

  const body = readFileSync(sourcePath, "utf-8")
  const header = [
    `# AUTO-GENERATED by npm run env:select — do not edit by hand for long-lived secrets.`,
    `# Edit ${envFileName(env)} instead, then re-run env:select (or npm run dev).`,
    `# APP_ENV=${env}`,
    `# SELECTED_FROM=${envFileName(env)}`,
    `# SOURCE=${source}${branch ? ` branch=${branch}` : ""}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
  ].join("\n")

  const withAppEnv = body.includes("APP_ENV=")
    ? body.replace(/^APP_ENV=.*$/m, `APP_ENV=${env}`)
    : `APP_ENV=${env}\n${body}`

  writeFileSync(targetPath, `${header}${withAppEnv.endsWith("\n") ? withAppEnv : `${withAppEnv}\n`}`, "utf-8")

  // Keep a convenience copy path for tools that still look at .env (gitignored)
  copyFileSync(targetPath, resolve(process.cwd(), ".env"))

  console.log(
    `[env] Selected APP_ENV=${env} from ${envFileName(env)} (${source}${branch ? `, branch=${branch}` : ""}) → .env.local`
  )
}

try {
  selectEnv()
} catch (err) {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
}

// Re-export for typed consumers / tests
export type { AppEnv }
